DB_CONFIG:
  name: "hole-dev"
  type: "mysql"
  host: "localhost"
  port: "3306"
  username: "root"
  password: "root"
  database: "hole-dev"
  synchronize: true

AVATAR_URL: "https://api.multiavatar.com/"
